services:
  postgres:
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - quote-editor-postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6.2
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  quote-editor-postgres-data:
  redis-data:
